# Generated by Django 4.2.5 on 2024-07-22 08:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise")),
                ('image_breadcrumb', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='breadcrumb image')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='brochure')),
                ('image_high', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_1')),
                ('image_low', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_2')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('about_high', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos')),
                ('about_low', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page a propos 2')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du client')),
                ('logo', models.ImageField(upload_to='images/clients', verbose_name='Logo du client')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer le client')),
            ],
            options={
                'ordering': ['ordering', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone')),
                ('niveau', models.CharField(blank=True, choices=[('S1', 'Cycle Moyen'), ('S2', 'Niveau Secondaire'), ('S3', 'Niveau Terminal'), ('S4', 'Formation Professionnelle '), ('S5', 'Baccalauréat'), ('S6', 'Niveau Universitaire')], max_length=2, null=True, verbose_name="niveau d'étude")),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True, verbose_name='lieu de naissance')),
                ('permis', models.BooleanField(default=False, verbose_name='Permis de Conduire ')),
                ('passeport', models.BooleanField(default=False, verbose_name='Passeport valide')),
                ('army', models.BooleanField(default=False, verbose_name='Service militaire')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Experience')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='media', verbose_name='CV')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'hiring',
                'verbose_name_plural': 'hirings',
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Chiffre')),
                ('text', models.TextField(verbose_name='Achievment detail')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer le client')),
            ],
            options={
                'ordering': ['ordering', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProtfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la categorie')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la categorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer la categorie')),
            ],
            options={
                'verbose_name': 'Categorie de portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='service title')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='service title')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='service title')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='service title')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='URL')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('display_on_home', models.BooleanField(default=False, verbose_name='Display on home page')),
                ('description', models.TextField(blank=True, null=True, verbose_name='service samll description ')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='service samll description ')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='service samll description ')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='service samll description ')),
                ('image_breadcrumb', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='breadcrumb image')),
                ('icon', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image du service')),
                ('image_high', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_detail_1')),
                ('image_low', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_detail_2')),
                ('full_description_1', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1')),
                ('full_description_1_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1')),
                ('full_description_1_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1')),
                ('full_description_1_fr', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1')),
                ('full_description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2')),
                ('full_description_2_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2')),
                ('full_description_2_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2')),
                ('full_description_2_fr', tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['ordering', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la solution')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nom de la solution')),
                ('name_ar', models.CharField(max_length=50, null=True, verbose_name='Nom de la solution')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='Nom de la solution')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution')),
                ('title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution')),
                ('title_ar', models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution')),
                ('title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='Grand titre de la solution')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/solutions', verbose_name='Petite image')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/solutions', verbose_name='Grande image')),
                ('text', models.TextField(blank=True, null=True, verbose_name='petit texte')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='petit texte')),
                ('text_ar', models.TextField(blank=True, null=True, verbose_name='petit texte')),
                ('text_fr', models.TextField(blank=True, null=True, verbose_name='petit texte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer la solution')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service')),
                ('description_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service')),
                ('description_fr', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du service')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('job_title', models.CharField(max_length=80, verbose_name='Fonction')),
                ('image', models.ImageField(upload_to='images/team/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('entreprise', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'entreprise")),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'item")),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL de la video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/portfolio', verbose_name="Image de l'item")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'item")),
                ('is_active', models.BooleanField(default=True, verbose_name="Activer l'item")),
                ('display_on_home', models.BooleanField(default=False, verbose_name='Display on home page')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='core.protfoliocategory', verbose_name='categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom')),
                ('entreprise', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'entreprise")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone')),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='sujet')),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
            },
        ),
    ]
