# Generated by Django 4.2.5 on 2024-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_contact_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('job_title', models.CharField(max_length=80, verbose_name='Fonction')),
                ('image', models.ImageField(upload_to='images/team/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
