# Generated by Django 4.2.5 on 2024-07-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordering', '-id'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
    ]
