# Generated by Django 4.2.5 on 2024-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_teammember_facebook_teammember_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.AddField(
            model_name='service',
            name='display_on_home',
            field=models.BooleanField(default=False, verbose_name='Display on home page'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyItem',
        ),
    ]
