# Generated by Django 4.2.5 on 2024-07-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_companyitem_company_remove_service_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la categorie')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la categorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer la categorie')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'item")),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL de la video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/portfolio', verbose_name="Image de l'item")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'item")),
                ('is_active', models.BooleanField(default=True, verbose_name="Activer l'item")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='core.protfoliocategory', verbose_name='categorie')),
            ],
        ),
    ]
