# Generated by Django 4.2.5 on 2024-07-21 10:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_service_description_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='about_high',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_high_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_high_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_high_fr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_low',
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='service samll description '),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='service samll description '),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='service samll description '),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_1',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_1_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_1_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_1_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_2',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_2_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_2_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_2_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='full Text service 2'),
        ),
    ]
