# Generated by Django 4.2.5 on 2024-07-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_service_about_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='display_on_home',
            field=models.BooleanField(default=False, verbose_name='Display on home page'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='service', max_length=100, verbose_name='service title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='service title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='service title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='service title'),
        ),
    ]
