# Generated by Django 4.2.5 on 2024-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du client')),
                ('logo', models.ImageField(upload_to='images/clients', verbose_name='Logo du client')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer le client')),
            ],
        ),
        migrations.AlterModelOptions(
            name='protfoliocategory',
            options={'verbose_name': 'Categorie de portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
    ]
