# Generated by Django 4.2.5 on 2024-07-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_client_alter_protfoliocategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Nom du client')),
                ('text', models.TextField(verbose_name='Achievment detail')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activer le client')),
            ],
        ),
    ]
