# Generated by Django 4.2.5 on 2024-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Chiffre'),
        ),
    ]
