# Generated by Django 4.2.5 on 2024-07-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_proof_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['ordering', '-id']},
        ),
        migrations.AlterModelOptions(
            name='proof',
            options={'ordering': ['ordering', '-id']},
        ),
    ]
