# Generated by Django 4.2.5 on 2024-07-22 08:57

import colorfield.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logos', verbose_name='Logo')),
                ('logo_negatif', models.ImageField(blank=True, null=True, upload_to='images/slides', verbose_name='Logo négatif')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/logos', verbose_name='Favicon')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Adresse')),
                ('address_link', models.CharField(blank=True, max_length=50, verbose_name='Lien maps ')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name="email de l'entreprise")),
                ('email2', models.EmailField(blank=True, max_length=50, verbose_name="2eme email de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name="numéro de téléphone de l'entreprise")),
                ('phone2', models.CharField(blank=True, max_length=50, verbose_name="2eme numéro de téléphone de l'entreprise")),
                ('phone3', models.CharField(blank=True, max_length=50, verbose_name="3eme numéro de téléphone de l'entreprise")),
                ('work_start', models.TimeField(verbose_name='heure de debut ')),
                ('work_end', models.TimeField(verbose_name='heure de fin ')),
                ('about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos')),
                ('conditions', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conditions d utilisations')),
                ('mini_about', models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)")),
                ('facebook', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Facebook')),
                ('instagram', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Instagram')),
                ('tiktok', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Tiktok')),
                ('twitter', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte Twitter (X)')),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte linkedin')),
                ('youtube', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Chaine Youtube')),
                ('chat_code', models.TextField(blank=True, null=True, verbose_name='Script messagerie instantané')),
                ('pixel', models.TextField(blank=True, null=True, verbose_name='Script Facebook pixel')),
                ('analytics', models.TextField(blank=True, null=True, verbose_name='Script Analytics')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='SEO description ')),
                ('meta_keyword', models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO keywords')),
                ('contact_message', models.TextField(blank=True, null=True, verbose_name='Contact message')),
                ('google_maps', models.TextField(blank=True, null=True, verbose_name='iframe google maps')),
                ('theme_color', colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Theme color')),
                ('theme_text_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Text color')),
                ('header_color', colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Navigation bar color')),
                ('header_hover_color', colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Navigation hover color')),
                ('header_text_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Navigation bar text color')),
                ('footer_color', colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Footer color')),
                ('footer_text_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Footer text color')),
                ('buttons_color', colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Button color')),
                ('buttons_hover_color', colorfield.fields.ColorField(blank=True, default='#011627', image_field=None, max_length=25, null=True, samples=None, verbose_name='Button hover color')),
                ('buttons_text_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Button text color')),
                ('banner_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Banner background ')),
                ('banner_text_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Banner text color')),
                ('banner_maintext_color', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None, verbose_name='Banner main text color')),
            ],
            options={
                'verbose_name': '1- Infomation',
                'verbose_name_plural': '1- Infomations',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Slide haut de page')),
                ('placement', models.PositiveSmallIntegerField(choices=[(1, 'Home page About section'), (2, 'About Page'), (3, 'Contact Page')], default=1, verbose_name='Slide emplacement')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
                'ordering': ['ordering', '-id'],
            },
        ),
    ]
