# Generated by Django 4.2.5 on 2024-07-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_delete_about_remove_contact_service_delete_hiring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='actif',
            new_name='is_active',
        ),
    ]
