# Generated by Django 4.2.5 on 2024-07-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_slide_options_rename_photo_slide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='placment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Home page About section'), (2, 'About Page'), (3, 'Contact Page')], default=1, verbose_name='Slide emplacement'),
        ),
    ]
