# Generated by Django 4.2.5 on 2024-07-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_slide_placment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='placment',
            new_name='placement',
        ),
    ]
